defaults:
  - aquisitionFunction: UpperConfidenceBound
  - surrogateFunction: HeteroskedasticSingleTaskGP
  - benchmark: branin
  - experimentConfig: s2b2eTsF
  - _self_

hydra:
  sweeper:
    params:
      aquisitionFunction: glob(*)
      surrogateFunction: HeteroskedasticSingleTaskGP
      benchmark: glob(*)
      experimentConfig: s2b2eTsF
