defaults:
  - aquisitionFunction: expectedImprovement
  - surrogateFunction: SingleTaskGP
  - benchmark: Hartmann6
  - experimentConfig: s5b15eFsF
  - _self_

hydra:
  sweeper:
    params:
      aquisitionFunction: glob(*)
      surrogateFunction: glob(*)
      benchmark: glob(*)
      experimentConfig: s5b15eFsF